import type { GlossaryEntry } from "@/lib/types";

export const glossary: GlossaryEntry[] = [
  { term: "AoE", def: "'Area of effect' — a spell that hits every enemy at once (Meteor Strike, Tempest, Scarecrow). The backbone of fast questing; also called 'attack-all'.", also: ["attack-all", "hit-all"] },
  { term: "Aura", def: "A self-buff that lasts several rounds (e.g. damage-boosting Star school spells). Only one aura active on you at a time — casting a new one replaces it." },
  { term: "Bazaar", def: "The secondhand shop in Olde Town (Wizard City) where players' sold items are resold cheap. Your gear source while leveling and reagent marketplace forever." },
  { term: "Blade", def: "A charm placed on yourself (or an ally) that multiplies their next outgoing hit — e.g. +35%. Consumed by the next qualifying attack." },
  { term: "Block", def: "Critical block rating reduces the chance an incoming critical hit actually crits. The defensive half of the crit arms race." },
  { term: "Cheat / cheat boss", def: "A boss with scripted rule-breaking behavior ('when you trap me, I remove it and counterattack'). Announced via dialogue lines; beaten by learning the script." },
  { term: "Charm", def: "Any effect hanging on a wizard that modifies their outgoing casts — blades are positive charms, weaknesses are negative ones." },
  { term: "Crowns", def: "The premium currency, bought with real money (small amounts earnable via trivia). Buys areas permanently, packs, mounts, elixirs, and convenience." },
  { term: "Critical", def: "A chance-based bonus that amplifies a hit (or heal). Driven by critical rating from gear/pets; countered by the target's block rating." },
  { term: "Deckathalon", def: "A recurring event: solo tower climbs where only treasure cards may be used — a deckbuilding puzzle mode with spellement/pet rewards." },
  { term: "Dispel", def: "A debuff forcing the target's next spell of a given school to fizzle. PvP staple, situational PvE tech." },
  { term: "DoT", def: "'Damage over time' — spells that burn/bleed across following rounds (Fire Elf, Deer Knight). Applied damage keeps ticking even through shields raised afterward.", also: ["overtime", "burn"] },
  { term: "Drain", def: "Death-school attacks that heal the caster for a portion (typically half) of damage dealt — the engine of Death's solo power." },
  { term: "Elder harvest", def: "A plant's final, biggest harvest at the end of its life cycle — the payout event of gardening, usually returning seeds to replant." },
  { term: "Energy", def: "The shared resource spent on pet training, gardening, fishing, and monstrology extracts. Regenerates over time; expanded by gear and membership." },
  { term: "Enchant", def: "A card played onto another card to upgrade it — most importantly Sun school damage enchants (Colossal etc.) added to attacks before or during fights.", also: ["treasure card enchant"] },
  { term: "Farming", def: "Repeatedly defeating a boss/dungeon for its drops — gear, gold, spells, spellements. Half the endgame, all of the economy." },
  { term: "Feint", def: "Death trap: ~+70% damage on the target's next received hit (with a small backlash trap on you). One pip. The best damage utility in the game — everyone trains it." },
  { term: "First-gen pet", def: "A pet obtained from a drop/vendor rather than hatching — its talent pool is the 'wild' baseline breeders then refine." },
  { term: "Fizzle", def: "A failed cast due to accuracy. You lose the round but keep your pips. Storm's oldest enemy." },
  { term: "Gambit", def: "PvP-era spell classes with conditional effects — part of the modern arena's rock-paper-scissors layer. Rules shift with balance patches." },
  { term: "Gauntlet", def: "A placeable housing dungeon (usually from bundles) — a private, re-runnable multi-boss instance at your castle." },
  { term: "Global", def: "A field spell affecting everyone in the duel (both teams) until replaced — e.g. damage-boosting bubbles. Only one active at a time." },
  { term: "Henchman", def: "A crowns-rented ally summoned mid-fight from the shop button — the solo player's panic button for walls." },
  { term: "HoT", def: "'Heal over time' — healing spread across rounds (Sprite, Availing Hands-style spells).", also: ["heal over time"] },
  { term: "Item card", def: "A spell card granted by equipped gear (or pets). Counts as a separate source for stacking — item blades stack with trained blades." },
  { term: "Jewel", def: "A socketable stat gem inserted into gear slots (and pet jewel slots). Endgame stat-tuning; crafted or dropped." },
  { term: "Lore spell", def: "Off-school learnable spells originally dropped by the Loremaster in Dragonspyre (Deer Knight and friends) — also craftable or upgradeable via spellements." },
  { term: "Mastery amulet", def: "An amulet letting power pips count for a second school — the item that makes off-school builds (like a Fire healer) real." },
  { term: "May-cast", def: "A pet talent that randomly casts a spell (heal, blade, shield) on triggers during combat. 'May cast Fairy Friend' = beloved babysitter." },
  { term: "Mega snack", def: "High-rank pet snacks giving huge pet XP — the fuel of pet training, grown via gardening (Couch Potatoes, Evil Magma Peas)." },
  { term: "Minion", def: "A summoned ally creature (Myth's specialty). Takes its own turns; early-game soloing gold." },
  { term: "Monstrology", def: "The creature-collection system: extract animus from monsters to craft summons, house guests, and expels. The tome is the wizard Pokédex." },
  { term: "Mount", def: "Rideable speed boost (typically +40% movement). The single best quality-of-life purchase in the game." },
  { term: "Pierce", def: "Armor-piercing % ignores that much of the target's resist (and shields). The endgame's headline offensive stat.", also: ["armor pierce"] },
  { term: "Pip", def: "The action currency gained each round; spells cost pips. White = 1, power pip = 2 (for your school). Everything is pip math eventually." },
  { term: "Power pip", def: "A pip worth 2 for spells of your own school (and mastery schools). Power pip chance % is a core stat." },
  { term: "Prism", def: "A ward converting incoming damage of one school to its opposite — how Fire wizards fight Fire bosses without crying." },
  { term: "Reagent", def: "Crafting materials — harvested from world spawns, dropped, fished, gardened, or Bazaar-bought (Black Lotus, Ore, Amber…)." },
  { term: "Realm", def: "A parallel copy of the game world; switch freely via the realm menu. 'Realm hopping' re-harvests reagent spawns across copies.", also: ["realm hopping"] },
  { term: "Resist", def: "Percentage reduction of incoming damage of a school (universal resist covers all). Ice's specialty; every tank's favorite number." },
  { term: "Roshambo", def: "Community/official shorthand for the modern PvP counter-system layers (types of charms/wards interacting rock-paper-scissors style)." },
  { term: "Shadow magic", def: "The endgame magic system unlocked late in Arc 2 — shadow pips fuel powerful shadow-enhanced spells; archmastery governs pip generation in the modern game." },
  { term: "Shield", def: "A ward reducing the next incoming hit of given school(s) — Tower Shield (-50% universal) is the icon. Consumed on use; pierced by pierce." },
  { term: "Sideboard", def: "Your deck's treasure-card section — drawn manually with the draw triangle instead of clogging your normal hand.", also: ["TC sideboard"] },
  { term: "Sigil", def: "The glowing entry pads before dungeons/instances — step on to start the countdown. 'Sigil-sitting' = waiting there to pull passersby in." },
  { term: "Spellement", def: "Per-spell upgrade tokens: collect enough to advance a spell along an upgrade path (better numbers, branch variants). From events, key bosses, packs." },
  { term: "Spritely", def: "The iconic pet may-cast heal-over-time. Old faithful of solo questers since the pet system's dawn." },
  { term: "Stacking", def: "Layering multiple multiplicative buffs (blades/traps from different sources) on one hit. The core damage skill — see the strategy guides." },
  { term: "Stitching", def: "Paying crowns to move one item's appearance onto another's stats — how everyone looks good in Waterworks gear." },
  { term: "Stun", def: "Prevents the target's next action. Stun-block wards counter; bosses often carry stun immunity (cheats)." },
  { term: "TC", def: "'Treasure card' — single-use spell cards stored in the sideboard, tradeable between players. Emergency heals, extra damage, utility.", also: ["treasure card"] },
  { term: "Team-Up", def: "The kiosk matchmaking system for dungeons/bosses — queue with strangers, defeat content, exchange thanks and friend requests." },
  { term: "Trap", def: "A ward on an enemy multiplying the next hit they take (+25%-ish; Feint's +70% is the king). Consumed on use." },
  { term: "Triangle (draw)", def: "The in-combat button for drawing treasure cards from your sideboard — discard from hand first if you're full." },
  { term: "Ward", def: "Any effect hanging on a combatant that modifies incoming spells — shields and traps are wards (helpful and harmful respectively)." },
  { term: "Weakness", def: "A negative charm reducing the target's next outgoing hit — the mirror image of a blade; PvP currency." },
  { term: "Wisp", def: "The floating health/mana orbs scattered around worlds — free top-ups between fights. Mana wisps kept generations of wizards solvent." },
  { term: "X-pip spell", def: "A spell costing all your pips and scaling with the amount spent (Tempest, Judgement, Dryad). Patience converted to output." },
  { term: "Zeke", def: "Prospector Zeke, the collectible-quest NPC in every world — his quest pays one full training point per world. Always take it.", also: ["prospector zeke"] },
];
