import type { School } from "@/lib/types";

export const schools: School[] = [
  {
    slug: "fire",
    name: "Fire",
    emoji: "🔥",
    color: "#f4623a",
    title: "The School of Fire",
    tagline: "Burn now, burn later: damage that keeps ticking.",
    archetype: "Damage-over-time powerhouse",
    newPlayerFriendliness: "Very friendly",
    baseAccuracy: "~75%",
    overview: [
      "Fire is the school of passion and Pyromancers, and its gameplay identity is **sustained burn**: strong up-front hits plus damage-over-time (DoT) effects that keep working while you set up your next move. Statistically it sits just below Storm in raw damage while carrying meaningfully better accuracy and health — the 'almost-a-cannon that rarely misfires'.",
      "That combination makes Fire arguably the smoothest questing school in the game: enough damage to end fights fast, enough durability to survive mistakes, and DoTs that punch through annoying defenses (a burn keeps ticking behind shields once applied).",
    ],
    strengths: [
      "Top-tier questing speed — excellent AoE options across the whole leveling curve",
      "DoTs neutralize shield-heavy enemies and cheat mechanics that punish big single hits",
      "Solid accuracy and health for a damage school",
      "Endgame farming meta staple alongside Storm",
    ],
    weaknesses: [
      "Slightly behind Storm's ceiling for one-turn nukes",
      "DoT damage is spread over rounds — impatient players sometimes overkill instead",
      "Mid accuracy still means occasional fizzle pain before gear fixes it",
    ],
    signatureSpells: [
      { name: "Fire Elf", role: "Early DoT", note: "The spell that teaches you what burns are for" },
      { name: "Meteor Strike", role: "AoE workhorse", note: "Your street-clearing button for a huge stretch of the game" },
      { name: "Fire Dragon", role: "AoE + DoT finisher", note: "The iconic 'everything is on fire now' arc-one capstone" },
      { name: "Efreet", role: "Single-target nuke + debuff", note: "Big hit that also slaps a massive weakness on the target" },
      { name: "Rain of Fire era AoEs", role: "Endgame burns", note: "Later AoE-DoTs that define Fire's max-level farming loops" },
    ],
    statPriorities: [
      "Damage % first — Fire multiplies it across initial hits and every tick",
      "Accuracy early (until gear makes fizzles rare)",
      "Pierce at endgame, as enemy resist climbs",
      "Enough health/resist to shrug a counterattack — Fire can afford some greed",
    ],
    secondaries: [
      { pick: "Death to Feint", why: "The universal answer — boss damage in one pip" },
      { pick: "Ice to Tower Shield", why: "Patches the glass in glass-adjacent-cannon" },
      { pick: "Life to Sprite/Satyr (solo players)", why: "A heal button turns close calls into non-events" },
    ],
    levelingTips: [
      "Blade → Meteor is your whole early game; lean into it",
      "Cast the DoT *before* shields go up when you can — burns already ticking ignore later wards",
      "Against Fire-resistant enemies, carry a Prism (converts your hit to the opposite school)",
      "Your AoE curve is generous — rebuild your deck around each new one the level you learn it",
    ],
    funFact:
      "Fire's professor, Dalia Falmea, is one of the few Ravenwood teachers whose classroom has never exploded. The irony is noted by everyone.",
  },
  {
    slug: "ice",
    name: "Ice",
    emoji: "❄️",
    color: "#67c8f0",
    title: "The School of Ice",
    tagline: "You cannot lose a fight you refuse to die in.",
    archetype: "The immovable tank",
    newPlayerFriendliness: "Very friendly",
    baseAccuracy: "~80%",
    overview: [
      "Ice is the school of endurance: the highest health, the best defensive tools (Tower Shield is Ice's gift to the Spiral), and gear that stacks resist until enemy hits read like typos. Thaumaturges trade killing speed for near-immortality.",
      "Modern Ice is not damage-less — its kit grew real teeth over the years — but the identity holds: you win by still being there after everyone else's mistakes. Ice is the most forgiving school for learning the game, the beloved 'second wizard' for PvP, and the eternal tank in team content.",
    ],
    strengths: [
      "Highest base health and premier defensive spell kit",
      "Extremely forgiving — mistakes that kill a Storm wizard are Tuesday for Ice",
      "Tower Shield, taunts, and stuns make Ice the natural team tank",
      "Historically excellent in PvP thanks to outlast strategies",
    ],
    weaknesses: [
      "Fights take longer solo — modest damage means more rounds",
      "Can breed bad habits (surviving instead of ending fights)",
      "Team content sometimes just wants more damage, not more tank",
    ],
    signatureSpells: [
      { name: "Tower Shield", role: "The defensive icon", note: "-50% to the next hit; every school trains it, Ice owns it" },
      { name: "Evil Snowman", role: "Single-target staple", note: "The dependable mid-pip hit of the early-mid game" },
      { name: "Blizzard", role: "AoE workhorse", note: "Street-clearing on a budget" },
      { name: "Frost Giant era AoEs", role: "AoE + control", note: "Ice's big spells love adding stuns and disruption to damage" },
      { name: "Snow Angel", role: "AoE DoT + taunt era", note: "The farming-tank special: damage over time while enemies swing at you" },
    ],
    statPriorities: [
      "Resist — Ice gear stacks it into absurdity; lean in",
      "Health second (it multiplies with your healing and absorbs)",
      "Damage % to keep fights moving — don't go full turtle while questing",
      "Power pips for consistent big-spell turns",
    ],
    secondaries: [
      { pick: "Death to Feint", why: "Ice's fix for 'fights take forever': multiply the hits you do make" },
      { pick: "Life heals", why: "Resist + heals is the full immortality package for soloing" },
      { pick: "A damage school's blade (later, situational)", why: "Any extra multiplier helps the tank hit back harder" },
    ],
    levelingTips: [
      "Quest with damage gear, keep a resist set for hard bosses — full-tank questing is slow",
      "Feint + your AoE turns 'eventually' into 'now'; train it early",
      "You can facetank most cheat mechanics other schools dance around — abuse that in dungeons",
      "In teams, announce you'll tank/taunt; a coordinated hitter behind an Ice wall is the classic dungeon engine",
    ],
    funFact:
      "Ice students study in a literal ice cave attached to Ravenwood because their school building fell into the sky during the Dragon Titan war. They consider this fine.",
  },
  {
    slug: "storm",
    name: "Storm",
    emoji: "⚡",
    color: "#a259e6",
    title: "The School of Storm",
    tagline: "The biggest numbers in the Spiral, terms and conditions apply.",
    archetype: "Glass cannon",
    newPlayerFriendliness: "Challenging",
    baseAccuracy: "~70%",
    overview: [
      "Storm is the damage ceiling of Wizard101: the highest base spell damage, the most feared nukes, and endgame gear that turns Diviners into one-turn deleters of entire boss fights. The bill for all that power arrives as the lowest health in the game and the worst base accuracy — a fizzle at the wrong moment is Storm's signature tragedy.",
      "Storm rewards players who plan: build the blades, count the pips, land the one hit that ends everything. Played sloppily it's the fastest route to the defeat screen; played well it makes every other school feel slow. Veterans adore it; brand-new players should know what they're signing up for.",
    ],
    strengths: [
      "Highest damage output in the game, full stop",
      "Best-in-class AoE nukes make it the farming meta's favorite hitter",
      "Tempest (X-pip AoE) scales perfectly from street trash to bosses",
      "Utility surprises: charm removal, accuracy debuffs, shield-breaking tech",
    ],
    weaknesses: [
      "Lowest health — mistakes are lethal well into the endgame",
      "~70% base accuracy stings until gear and enchants patch it",
      "Pip-hungry: big turns need setup rounds that enemies get to interrupt",
    ],
    signatureSpells: [
      { name: "Kraken", role: "Early boss-killer", note: "The first 'oh, Storm is different' moment" },
      { name: "Tempest", role: "X-pip AoE", note: "Spend everything, hit everyone, scale forever — Storm's flexible core" },
      { name: "Storm Lord", role: "AoE + stun", note: "The arc-one capstone: massive damage and a board stun" },
      { name: "Sirens", role: "AoE + debuffs", note: "Damage plus accuracy sabotage — Storm's utility era begins" },
      { name: "Wild Bolt", role: "The meme", note: "Ask a veteran about original Wild Bolt and watch their eye twitch" },
    ],
    statPriorities: [
      "Accuracy until fizzle stops being a lifestyle (~gear-dependent)",
      "Damage % — your multiplier on the biggest base numbers in the game",
      "Pierce at endgame; resist means nothing to you if you're dead, so…",
      "…health/resist wherever it's free; Storm gear increasingly offers real defense",
    ],
    secondaries: [
      { pick: "Ice to Tower Shield", why: "Mandatory-adjacent: you must survive the setup rounds" },
      { pick: "Life to Satyr", why: "Solo Storm without a heal is speed-running the defeat animation" },
      { pick: "Death to Feint", why: "As if Storm needed more multiplier — but yes, more multiplier" },
    ],
    levelingTips: [
      "Carry shields from level 1; casting Tempest requires being alive",
      "Pass to bank pips more than any school — Tempest math rewards patience",
      "Accuracy enchants and gear save more damage than damage gear early (a fizzle is -100%)",
      "In teams, you are the hitter; politely accept everyone's blades, then justify them",
    ],
    funFact:
      "Storm professor Halston Balestrom is a frog. A brilliant, kinetic, endlessly enthusiastic frog. Storm students insist this explains everything about the school.",
  },
  {
    slug: "myth",
    name: "Myth",
    emoji: "👁️",
    color: "#e8c94a",
    title: "The School of Myth",
    tagline: "Why fight alone? Bring creatures. Hit twice. Break their toys.",
    archetype: "Minions, double-hits & disruption",
    newPlayerFriendliness: "Friendly",
    baseAccuracy: "~80%",
    overview: [
      "Myth is the school of imagination and Conjurers — mechanically, the school of *tricks*. Its kit is built on summonable minions, double-hit spells that slap twice in one card (breaking a shield with the first tap and landing the real hit with the second), and the Spiral's best disruption: Earthquake-style effects that wipe enemy buffs entirely.",
      "That toolbox play makes Myth the thinking player's damage school: not quite Storm's ceiling, but always holding an answer. Its minions carry early soloing; its shield-breakers and buff-strippers laugh at defensive bosses; its stuns control entire rooms.",
    ],
    strengths: [
      "Double-hit spells make shields nearly irrelevant against you",
      "Earthquake-line disruption deletes enemy blades/shields — cheat-fight gold",
      "Strong minions for early solo play; strong stuns for group control",
      "Healthy damage with respectable accuracy and cost curves",
    ],
    weaknesses: [
      "Minions fall off in relevance at higher levels",
      "The toolkit demands game knowledge — Myth punishes autopilot",
      "AoE curve arrives slightly awkwardly compared to Fire/Storm",
    ],
    signatureSpells: [
      { name: "Minion line (Troll → Cyclops → …)", role: "Summons", note: "Your early-game questing partner, no friends required" },
      { name: "Minotaur", role: "Double-hit", note: "Tap-then-slam: the anti-shield template Myth builds on" },
      { name: "Humongofrog", role: "AoE workhorse", note: "Yes, it vomits on everyone. It's very effective." },
      { name: "Earthquake", role: "AoE + full debuff strip", note: "Removes enemy blades and shields — the boss-setup eraser" },
      { name: "Orthrus / Medusa era", role: "Capstone double-hits & stuns", note: "Arc-defining damage with control stapled on" },
    ],
    statPriorities: [
      "Damage % — Myth's multipliers apply to both halves of double-hits",
      "Power pips for the minion + attack rhythm",
      "Accuracy to protect your combo turns",
      "Standard endgame pierce/crit progression thereafter",
    ],
    secondaries: [
      { pick: "Death to Feint", why: "Universal law, Myth chapter" },
      { pick: "Life heals", why: "Minions distract, but you still need a real heal button solo" },
      { pick: "Ice to Tower Shield", why: "Cheap insurance for setup turns" },
    ],
    levelingTips: [
      "Summon the minion turn one in solo fights, then build while enemies split attention",
      "Save double-hits for shielded enemies; use plain hits otherwise — sequencing is Myth's skill",
      "Earthquake is a *strategy*, not just a spell: bosses that stack defenses fold to it",
      "Stun coordination in teams (stun turn = free setup turn) makes Myth beloved in dungeons",
    ],
    funFact:
      "Myth's professor, Cyrus Drake, spends Arc 1 being the meanest teacher in Ravenwood for reasons that eventually make everyone apologize to him. Mostly.",
  },
  {
    slug: "life",
    name: "Life",
    emoji: "🌿",
    color: "#58c26a",
    title: "The School of Life",
    tagline: "The Spiral's healer — and quietly, a wall that hits back.",
    archetype: "Healer-sustain, the safest solo school",
    newPlayerFriendliness: "Very friendly",
    baseAccuracy: "~90%",
    overview: [
      "Life is the school of healing and Theurgists, holding the game's best restorative magic: efficient single heals, heals-over-time, group resurrection-tier spells, and the highest base accuracy in the game (~90%) so its plans almost never fizzle. A Life wizard's health bar is a rumor to their enemies — it never seems to go down for long.",
      "The old joke was that Life killed things by boring them to death; modern Life has genuine AoE and damage support, making it merely *deliberate* rather than slow. Solo, it is nearly unkillable. In groups, it's the teammate everyone thanks. For a first wizard who never wants a game-over screen, Life is the canonical answer.",
    ],
    strengths: [
      "Best healing kit in the game by a wide margin",
      "~90% base accuracy — plans that simply happen",
      "Extremely safe solo; effectively immortal with sensible play",
      "Beloved in every group, from dungeon pickups to raid-tier content",
    ],
    weaknesses: [
      "Kill speed trails the damage schools, especially early",
      "AoE arrives later/slower than Fire/Storm equivalents in the early game",
      "Being everyone's healer can eclipse your own gameplay if you let it",
    ],
    signatureSpells: [
      { name: "Sprite", role: "Heal-over-time", note: "The tiny fairy that carries the entire early game" },
      { name: "Satyr", role: "Big single heal", note: "The gold-standard heal other schools spend points to borrow" },
      { name: "Rebirth", role: "Team heal + absorbs", note: "The 'everyone lives' button; dungeon-famous" },
      { name: "Centaur", role: "Single-target damage", note: "Proof Life can, in fact, hit things" },
      { name: "Forest Lord", role: "AoE capstone", note: "The moment Life questing changes gear entirely" },
    ],
    statPriorities: [
      "Outgoing healing % where offered — multiplies your identity",
      "Damage % for questing pace (yes, really — dead enemies need no heals)",
      "Power pips: heals and hits are both pip-hungry",
      "Resist to make your sustain math unbeatable",
    ],
    secondaries: [
      { pick: "Death to Feint", why: "Turns your modest hits into sufficient hits" },
      { pick: "Ice to Tower Shield", why: "Shield + heal loops are literally unkillable in most PvE" },
      { pick: "A hitter school's blades (team play)", why: "Your buffs on a Storm friend clear rooms faster than anything you'd cast" },
    ],
    levelingTips: [
      "Quest in damage gear; you are your own safety net already",
      "Blade first even as a healer — a bladed Centaur now beats a heal you won't need later",
      "Learn heal *thresholds* (what each spell restores vs incoming damage) and you'll never overheal-waste turns",
      "In groups, state upfront: 'I heal emergencies, otherwise I blade the hitter' — it's the correct meta and sets expectations",
    ],
    funFact:
      "Life's classroom tree, Blossom, is the perkiest tree in Ravenwood. Moolinda Wu, the cow professor, radiates such calm that students report fights simply feeling rude.",
  },
  {
    slug: "death",
    name: "Death",
    emoji: "💀",
    color: "#9aa3b2",
    title: "The School of Death",
    tagline: "Every attack is also lunch. The solo king since 2008.",
    archetype: "Drain-sustain — offense that heals you",
    newPlayerFriendliness: "Very friendly",
    baseAccuracy: "~85%",
    overview: [
      "Death is the school of Necromancers and the game's most elegant mechanical loop: **drain spells deal damage and heal you for a portion of it**. One card, both halves of survival. That self-sufficiency made Death the legendary solo school — no heals to train, no downtime, just an unbroken march through content.",
      "Beyond drains, Death owns the single most important utility spell in the game (**Feint**, which every other school pays training points to borrow), great debuffs, and a personality the community adores. Its damage sits comfortably mid-high; its effective durability, thanks to drains, rivals Ice in practice.",
    ],
    strengths: [
      "Drains = attacking and healing in the same card; peerless solo economy",
      "Feint is native — the game's best damage utility, free with your homework",
      "Strong debuff/utility identity (weaknesses, infections against enemy heals)",
      "Very forgiving accuracy (~85%) for a damage-capable school",
    ],
    weaknesses: [
      "The famous AoE gap: Death waited ages for a cheap attack-all (Deer Knight lore-spell exists for a reason)",
      "Drain halves don't heal teammates — solo tools, team responsibilities",
      "Mid ceiling: you'll rarely out-nuke Fire/Storm, just out-last them",
    ],
    signatureSpells: [
      { name: "Vampire", role: "Early drain", note: "The loop in miniature: hit for X, heal for half" },
      { name: "Feint", role: "+70% trap", note: "The best pip-for-damage card in the game; Death gets it as a birthright" },
      { name: "Wraith", role: "Big drain", note: "Arc-one capstone: boss-tier damage that refills your bar" },
      { name: "Scarecrow", role: "AoE drain", note: "Hit everyone, heal off everyone — farming royalty" },
      { name: "Deer Knight", role: "AoE DoT (lore spell)", note: "The famous fix for Death's AoE gap — farm or craft it via the Loremaster pipeline" },
    ],
    statPriorities: [
      "Damage % — it multiplies your healing too (drains heal off damage dealt)",
      "Power pips for the drain rhythm",
      "Standard pierce/crit climb at endgame",
      "Resist is luxury: your health bar is self-repairing",
    ],
    secondaries: [
      { pick: "Ice to Tower Shield", why: "The one gap drains don't cover: surviving the turn *before* you drain" },
      { pick: "Balance blades (Niles)", why: "More multipliers on drains = damage and healing at once" },
      { pick: "Sun enchants (as always)", why: "Enchanted drains restore comical amounts of health" },
    ],
    levelingTips: [
      "Solo confidently — your kit is designed for it; save Team-Up for true walls",
      "Chase Deer Knight (Loremaster drops, spellements, or crafting) once viable; it modernizes your whole questing loop",
      "Blade before draining: the heal scales with the damage, so buffs are double-value for you",
      "Infection-style anti-heals are your secret weapon into healing enemies — pack one or two always",
    ],
    funFact:
      "The Death school building fell off Ravenwood into Nightside before the story begins, so Death students commute through a waterfall to a gloomy annex. Property values remain surprisingly stable.",
  },
  {
    slug: "balance",
    name: "Balance",
    emoji: "⚖️",
    color: "#d9975a",
    title: "The School of Balance",
    tagline: "A little of everything, mastered: the Spiral's support engine.",
    archetype: "Support-generalist with a nuke button",
    newPlayerFriendliness: "Friendly",
    baseAccuracy: "~85%",
    overview: [
      "Balance is the odd school out — literally taught in Krokotopia rather than Ravenwood — and it plays like the game's toolbox: universal blades (Balanceblade, Bladestorm) and traps that buff *any* school, mass buffs/debuffs, mixed-school attacks, and Judgement, the X-pip guillotine that converts patience directly into damage.",
      "No school makes teammates stronger, and few soloists are as self-reliant once the toolkit clicks. The cost of 'a little of everything' is edge-cases: Balance enemies resist you while no Prism bails you out, and your best tools sometimes want a teammate to swing the sword. Flexible, clever, endlessly useful — Balance is the school for players who like being the answer.",
    ],
    strengths: [
      "Universal buffs (Balanceblade, Bladestorm, tri-blades) make every team better",
      "Judgement: X-pip single-target damage with legendary boss-deleting history",
      "Rich utility: mass shields/traps, weakness stacks, mana/pip tricks",
      "Comfortable accuracy and solid bulk; very few bad matchups in PvE",
    ],
    weaknesses: [
      "Against Balance enemies you lack a Prism escape hatch — awkward mirror fights",
      "Master-of-none damage curve between Judgement spikes",
      "The kit's depth is real complexity; Balance has the steepest 'played well vs badly' gap of the support schools",
    ],
    signatureSpells: [
      { name: "Sandstorm", role: "AoE workhorse", note: "The dependable street-sweeper of the early-mid game" },
      { name: "Judgement", role: "X-pip nuke", note: "All your pips, one number. Historic boss-killer, PvP legend" },
      { name: "Balanceblade & Bladestorm", role: "Universal buffs", note: "The reason every team wants a Balance friend" },
      { name: "Elemental/Spirit Blades & Traps", role: "Tri-buffs (Niles, Krokosphinx)", note: "The multi-school stacking toolkit — cheap to train, forever useful" },
      { name: "Power Nova / Ra era", role: "AoE capstones", note: "Big attack-alls with debuff riders as the arcs progress" },
    ],
    statPriorities: [
      "Power pips — Judgement math *is* pip math",
      "Damage % close behind",
      "Accuracy/pierce standard climb",
      "Health/resist generously provided by Balance gear traditions",
    ],
    secondaries: [
      { pick: "Life to Satyr", why: "The classic Balance dip: real heals complete the self-sufficiency kit" },
      { pick: "Death to Feint", why: "Feint into Judgement is a beautiful, terrible thing" },
      { pick: "Ice to Tower Shield", why: "Buy time to bank Judgement pips" },
    ],
    levelingTips: [
      "Learn Judgement breakpoints (pips × per-pip damage vs boss health) — one clean Judgement ends most Arc 1 bosses",
      "Visit Niles on the Krokosphinx the moment you can; the tri-blade/trap set is your stacking backbone",
      "In teams, buff the hitter and feel powerful about it — your blades win the fight, whoever animates the kill",
      "Against Balance mobs, lean on your off-school attack options (Hydra/Spectral-style) rather than fighting resist",
    ],
    funFact:
      "Balance students take a study-abroad program by default: their school hides beneath the Krokosphinx in Krokotopia, taught by Alhazred — with Arthur Wethersfield holding down a Ravenwood satellite desk.",
  },
];

export const schoolBySlug = new Map(schools.map((s) => [s.slug, s]));
